### ISSUE TITLE
As a developer, I want to have tests for all units of my program as well as integration tests and end-to-end tests to make sure that the program behaves as wanted

### ISSUE THREAD

**Issue by cyberkold** [ITU-BDSA23-GROUP1/Chirp#14]
### **Task description:**

- Restructure your current project so that the Chirp! application and the CSV database library reside under a src/ directory
- Hint: use git mv to move files and directories while restructuring.
- Create XUnit .NET test projects, see dotnet new list in a test directory that is in the root of your project, see e.g., page 880 of A. Lock ASP.NET Core in Action, Third Edition.
- That is, one test project that tests your Chirp! CLI app and a second one that tests your CSV database library project.
- Make your test projects depend on the respective system under test (SUT).
- That is, add a reference from each of the two test projects to either the Chirp! CLI app or to the CSV database library project with the [dotnet add reference](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-add-reference) command.
- Add unit tests to your Chirp! CLI app.
- Add unit tests for suitable functionality. For example, conversion of UNIX timestamps to user readable times and similar functionality are good candidates for unit testing.
- Add integration tests that test your CSV database library works as intended.
- For example, add a test case that checks that an entry can be received from the database after it was stored in there.
- Add two end-to-end tests that test your Chirp! CLI app:
- For example, you want to test that given example data from [chirp_cli_db.csv](https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_01/chirp_cli_db.csv) calling chirp read 10 from the command line produces output as in the following:
- ropf @ 08/01/23 14:09:20: Hello, BDSA students!
- rnie @ 08/02/23 14:19:38: Welcome to the course!
- rnie @ 08/02/23 14:37:38: I hope you had a good summer.
- ropf @ 08/02/23 15:04:47: Cheeping cheeps on Chirp :)
- Additionally, you want to test that calling chirp cheep "Hello!!!" stores the respective values in the database.

### **Acceptance criteria:**
- XUnit .NET is used for testing the program
- There are unit tests for all methods with relevant functionality
- The test projects depends on the respective system under test (SUT)
- There are integration tests for the CSV database library
- There is an end-to-end test for the Chrip! CLI app

**Comment by Carmish** [comment]
Unit- and Integrationtest done. We will get back to the End-to-end test.
