### ISSUE TITLE
As a developer, I want my database to run on SQL Server database so it is suitable for production and scaling up

### ISSUE THREAD

**Issue by cyberkold** [ITU-BDSA23-GROUP1/Chirp#70]
Rather than SQLite, we should use SQL server, so it can also be deployed to Azure.

Description from lecture:

Refactor your Chirp! application so that it uses an SQL Server database when executed locally. Such a database can be instantiated via docker for example as in the following:

- docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=yourStrong(!)Password" -p 1433:1433  --name sqlpreview --hostname sqlpreview -d mcr.microsoft.com/mssql/server:2022-latest
- Ensure your tests are still running - using SQLite in-memory and/or test containers.
- Run your production code with Azure SQL.
- Ensure you apply your migrations when deploying to App Services.
- Extend your CheepRepository to support create (test and implement).
- Using FluentValidation to ensure all inputs are valid.
- Add a Chirp! form to your app which is only visible when a user is signed in.
- Ensure a user can only post to the form if she is signed in.

Acceptance criteria:
-  a user can only post to the form if she is signed in.
- Production code can be run with Azure SQL.
- Chirp! form to your app is only visible when a user is signed in.

**Comment by Carmish** [comment]
all criteria are fulfilled
