### ISSUE TITLE
As a developer, I want the SQL database on Azure, so it's production ready

### ISSUE THREAD

**Issue by cyberkold** [ITU-BDSA23-GROUP1/Chirp#71]
Text from lecture:

See for example this guide: https://learn.microsoft.com/en-us/azure/azure-sql/database/single-database-create-quickstart?view=azuresql&tabs=azure-portal

Configure your Chirp! applications that are deployed to Azure App Service, i.e., your applications in production, to target this Azure SQL database.

The name of your database server is bdsagroup<no>-chirpdb, where <no> is replaced with your group number.

Remember to configure your Azure SQL Server to use SQL Login with a username and password to use for your connection string.

Note: The demo using Entra ID Groups and Managed Identity is not posible with your Azure Subscription on the ITU tenant. This is why we switch back to legacy SQL Login.

Acceptance criteria:
- The database is on a database server on Azure.
- The name of the database server is bdsagroup1-chirpdb

**Comment by Carmish** [comment]
all criteria are fulfilled
