### ISSUE TITLE
As a developer, I want to constrain the length of the cheeps to fit the requirements of the application.

### ISSUE THREAD

**Issue by cyberkold** [ITU-BDSA23-GROUP1/Chirp#74]
Text from lecture:

Constrain cheeps so that only cheeps of length 160 characters are considered valid. Your Chirp! application should not accept cheeps that are longer that 160 character. Such cheeps should never be stored to the database.

Using the mechanisms presented in chapter 18 of the course book Andrew Lock ASP.NET Core in Action, validate that only cheeps up to 160 characters length can be sent.

Acceptance criteria:

- Cheeps can only be 160 characters long.
- There should be a relevant error message if cheep gets too long, or the user should be prompted when reaching the maximum characters.

**Comment by Carmish** [comment]
We restricted the length of cheeps, so it isn't possible to write more than 160 characters. There isn't any error message and we aren't going to implement that.
