### ISSUE TITLE
As a user I want to be able to seee my personal information

### ISSUE THREAD

**Issue by olivia2300** [ITU-BDSA23-GROUP1/Chirp#98]
Add feature: User information page
After Jakob's lecture on GDPR, you learned that you have to be able to provide users information about their personal data that your application stores about them.

In the navigation bar on top, in between links to timelines and login, create a link to a new page with the link text "about me". That link appears only if a user is authenticated in your Chirp! application. If authenticated, a user should be able to see all information that your Chirp! application stores about her on that page. That is all personal information, like name, email address, links to other users that this user is following, etc. should be presented Additionally, all cheeps of this user are listed.

Optionally, you can implement functionality to download all this information as a zipped archive of text files. These might be CSV files, plain text files, etc.

**Acceptance criteria:**
- A link at the navigation bar that takes a user to a personal-information page.
- Besides user-information, all cheeps of this user should be listed on this page.
- The link should only be visible if a user is authenticated.

**Comment by Carmish** [comment]
all criteria are fulfilled.
