### ISSUE TITLE
As a user I want to be able to remove my account and forget all information about me.

### ISSUE THREAD

**Issue by AlexBjoornskov** [ITU-BDSA23-GROUP1/Chirp#99]
https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_12/README_PROJECT.md#add-feature-forget-me
**Forget me feature**
On the user information page, place a red button with the text Forget me!. An authenticated user can click this button. The system should then delete all information about this user, e.g., name, email address, links to other users that this user is following, etc. should be removed from your Chirp! application.

As you know from the lecture, there are various ways of implementing this feature. For this class and project, it is okay if you implement the technically most simply form of this feature as described in section 12.4.4 in [Andrew Lock ASP.NET Core in Action, Third Edition](https://www.manning.com/books/asp-net-core-in-action-third-edition). That is, so that a delete operation is not a real delete but an update operation that modifies the respective data so that it is not displayed anymore. This solution is of course not GDPR compliant.

Alternatively, since you remember from Jakob that in terms of GDPR "anonymization == deletion", you can decide to implement deletion in this way. That is, you may want to implement this feature so that user names and other personal data are anonymized For this project, it is okay that you do not consider anonymizing the contents of a cheep.

Acceptance criteria:
- A button to delete account/forget about user
- When button pressed all data about a user is deleted
- It should only be possible to find this button if you are logged in (authenticated)
- The button should say "Forget me!" and should be red

**Comment by Carmish** [comment]
all criteria are fulfilled
